# Generated by Django 6.0.2 on 2026-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='live_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
