# Generated by Django 6.0.2 on 2026-02-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolio_github_link_portfolio_live_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='screenshot',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('is_main', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.portfolio')),
            ],
        ),
    ]
