# Generated by Django 6.0.2 on 2026-03-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_portfolio_is_main_remove_portfolio_screenshot_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactModel',
        ),
    ]
